export enum AuthType {
  signup = "signup",
  signin = "signin",
}

export const fields = {
  [AuthType.signin]: [
    {
      labelText: "Email address",
      labelFor: "email-address",
      id: "email-address",
      name: "email",
      type: "email",
      autoComplete: "email",
      isRequired: true,
      placeholder: "Email address",
    },
    {
      labelText: "Password",
      labelFor: "password",
      id: "password",
      name: "password",
      type: "password",
      autoComplete: "current-password",
      isRequired: true,
      placeholder: "Password",
    },
  ],
  [AuthType.signup]: [
    {
      labelText: "Full name",
      labelFor: "full-name",
      id: "full-name",
      name: "fullname",
      type: "text",
      autoComplete: "name",
      isRequired: true,
      placeholder: "Full name",
    },
    {
      labelText: "Email address",
      labelFor: "email-address",
      id: "email-address",
      name: "email",
      type: "email",
      autoComplete: "email",
      isRequired: true,
      placeholder: "Email address",
    },
    {
      labelText: "Password",
      labelFor: "password",
      id: "password",
      name: "password",
      type: "password",
      autoComplete: "current-password",
      isRequired: true,
      placeholder: "Password",
    },
    {
      labelText: "Confirm Password",
      labelFor: "confirm-password",
      id: "confirm-password",
      name: "confirm-password",
      type: "password",
      autoComplete: "confirm-password",
      isRequired: true,
      placeholder: "Confirm Password",
    },
  ],
};
